### ISSUE TITLE
detect nested bbcodes

### ISSUE THREAD

**Issue by zloyrusskiy** [asceth/bbcoder#16]
Hi, i have messages with nested bbcode. I want to render them with indentation, but can't detect nesting level.

**Comment by asceth** [comment]
Can you give me an example of what you are trying to accomplish?  Nested tags should be supported, and from there defining CSS rules could give you the necessary margin/padding for indentation.

**Comment by zloyrusskiy** [comment]
I'm writing bot (for notifications about new messages on site with phpbb engine) for https://www.hipchat.com/. It has limited ability to control HTML presentation and no custom CSS, as i know.

You can bind *parents* method (with all parents for this tag) of processed tag to content rendering block, maybe?

**Comment by asceth** [comment]
That is a good scenario though the `parents` method is only for determining the prerequisite tags needed for the tag to be valid.  I will need to expose the chain of open tags to the element as its being turned into html so I can bind it.  I will look further into the details of providing this feature.

**Comment by asceth** [comment]
I've exposed the `depth` method to block in the https://github.com/asceth/bbcoder/tree/feature/expose_depth branch, if you want to try it out.  I'll take one more look at it before I merge to master and push a new version.  I'll add some documentation on the feature soon.

**Comment by zloyrusskiy** [comment]
Great! Works good!

**Comment by asceth** [comment]
Merged and released as 1.1.0
